# Generated by Django 5.2.6 on 2025-09-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='Fecha/hora inicio')),
                ('end_dt', models.DateTimeField(verbose_name='Fecha/hora fin')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Ausencia',
                'verbose_name_plural': 'Ausencias',
                'db_table': 'availability_timeoff',
                'ordering': ['-start_dt'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.location')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'availability_holiday',
                'ordering': ['date'],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('slot_every_min', models.PositiveIntegerField(default=20, verbose_name='Duración de slot (minutos)')),
                ('max_overbooking', models.PositiveIntegerField(default=0, verbose_name='Máximo sobrecupo')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='doctors.doctor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.specialty')),
            ],
            options={
                'verbose_name': 'Plantilla de horario',
                'verbose_name_plural': 'Plantillas de horario',
                'db_table': 'availability_scheduletpl',
                'ordering': ['doctor', 'weekday', 'start_time'],
                'unique_together': {('doctor', 'location', 'weekday', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='Fecha/hora inicio')),
                ('end_dt', models.DateTimeField(verbose_name='Fecha/hora fin')),
                ('status', models.CharField(choices=[('LIBRE', 'Libre'), ('BLOQUEADO', 'Bloqueado'), ('OCUPADO', 'Ocupado')], default='LIBRE', max_length=10)),
                ('source', models.CharField(choices=[('TPL', 'Plantilla'), ('EXCEPTION', 'Excepción')], default='TPL', max_length=10)),
                ('appointment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmenttype')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.doctor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
            options={
                'verbose_name': 'Franja disponible',
                'verbose_name_plural': 'Franjas disponibles',
                'db_table': 'availability_slot',
                'ordering': ['start_dt'],
                'indexes': [models.Index(fields=['doctor', 'start_dt'], name='availabilit_doctor__be4429_idx'), models.Index(fields=['location', 'start_dt'], name='availabilit_locatio_b9c6f5_idx')],
                'unique_together': {('doctor', 'start_dt', 'room')},
            },
        ),
    ]
