# Generated by Django 5.2.6 on 2025-09-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Tipo de objeto')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID del objeto')),
                ('action', models.CharField(max_length=50, verbose_name='Acción')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'db_table': 'audit_auditevent',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx'), models.Index(fields=['actor', 'at'], name='audit_audit_actor_i_6c9c9e_idx')],
            },
        ),
    ]
