# Generated by Django 5.2.6 on 2025-09-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('requires_room', models.BooleanField(default=True, verbose_name='Requiere sala')),
                ('requires_resource', models.JSONField(blank=True, default=list, verbose_name='Recursos requeridos')),
                ('buffer_before_min', models.PositiveIntegerField(default=0, verbose_name='Buffer antes (minutos)')),
                ('buffer_after_min', models.PositiveIntegerField(default=0, verbose_name='Buffer después (minutos)')),
            ],
            options={
                'verbose_name': 'Tipo de cita',
                'verbose_name_plural': 'Tipos de cita',
                'db_table': 'appointments_appointmenttype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO_PAC', 'Cancelado por paciente'), ('CANCELADO_CLIN', 'Cancelado por clínica'), ('NO_SHOW', 'No asistió'), ('ATENDIDO', 'Atendido')], default='RESERVADO', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de check-in')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de atención')),
                ('no_show_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='Marcado como no-show')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments_appointment',
                'ordering': ['-booked_at'],
            },
        ),
    ]
