# Generated by Django 5.2.6 on 2025-09-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Número de licencia')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('locations', models.ManyToManyField(related_name='doctors', to='core.location', verbose_name='Sedes')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'doctors_doctor',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
